### PR TITLE
Added local npm logo

### PR DESCRIPTION
**Pull request by nickcolley**

### CODE REVIEW

**Comment by nolanlawson** [comment]
GORGEOUS. I love it! Thank you!! :tada:

**Comment by bubkoo** [comment]
Cool...
Was the logo builded with online tools?

**Comment by nickcolley** [comment]
hey @bubkoo I use [inkscape](https://inkscape.org/en/) for any vector graphics.

:+1:

**Comment by bubkoo** [comment]
@nickcolley So you draw the font or just use any exited font, and what's the name of the font?

**Comment by zeke** [comment]
The font is called gubblebum

**Comment by nickcolley** [comment]
@bubkoo I drew it in illustrator didn't realise it was a font cool to know thanks @zeke

**Comment by bubkoo** [comment]
@all, thanks :+1:

**Pull request merged**
