### PR TITLE
Improved Markdown renderer

### PR DESCRIPTION
**Pull request by wmhilton**
### I'll happily hand it over. :)

Well... I'm not eager to be saddled with the responsibility of this great project, but that may be the price I pay, lol.

My first contribution - big impact, low effort! It's an enhancement to the Web UI only. I swapped out the markdown renderer for a better one. In fact, after a quick hack and a pull-request, I got the same Markdown renderer used by www.npmjs.com to work in the browser.

# BEFORE:
markdown

# AFTER:
marky-markdown

### CODE REVIEW

**Comment by wmhilton** [comment]
Oops, forgot the live demos:
Old renderer: http://registry.node-modules.io/_browse/#/local-npm
New renderer: http://www2.node-modules.io/_browse/#/local-npm

**Comment by nolanlawson** [comment]
Cool, this is really awesome! Thanks for the PR. :)

**Comment by wmhilton** [comment]
Thank *you* for being awesome! Updated http://registry.node-modules.io/_browse

**Comment by wmhilton** [comment]
close #110

**Comment by zeke** [comment]
Nice! I'm so happy to see that [in these dark times](http://blog.npmjs.org/post/148119862590/out-with-the-newww-and-in-with-the-www-an-update), some piece of the npm website still has an open-source future. Thanks for doing this, @wmhilton!

**Comment by wmhilton** [comment]
@zeke Feel free to publicize [node-modules.io](https://github.com/wmhilton/node-modules.io) - would love for it to become a hub for like-minded people interested in disrupting the npm monopoly.

**Pull request merged**
