### PR TITLE
(#37) - add shorthand for /pkg/version

### PR DESCRIPTION
**Pull request by nolanlawson**
After this fix, the following URLs all work:

* http://127.0.0.1:5080/jsbin/3
* http://127.0.0.1:5080/jsbin/3.11
* http://127.0.0.1:5080/jsbin/3.11.23

And this one throws a 404 error:

* http://127.0.0.1:5080/jsbin/3.11.1337

### CODE REVIEW

**Comment by remy** [comment]
Not to make you jump through all kinds of hoops, but does this work?

* http://registry.npmjs.org/jsbin/3.11.x

Because I'm slapping in semver ranges into the npm registry to find the latest match(!)

**Comment by nolanlawson** [comment]
Just tried it, and yes. :) I'm using the `semver` package to determine what matches.

**Comment by remy** [comment]
:facepunch: :heart:

**Comment by nolanlawson** [comment]
+1d by @calvinmetcalf, published as 1.4.2

**Pull request merged**
