### PR TITLE
fixes crashes due to lost of connection

### PR DESCRIPTION
**Pull request by DrorT**
Fix for issue https://github.com/nolanlawson/local-npm/issues/104 that I opened a few days ago

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks for the PR! Can you provide a little more detail on how exactly this fixes the issue? Looking at the code, it seems that you convert an error from `request` into a 500 error sent to the user. Seems this is exactly the same behavior that occurs when you pipe the response directly, so I don't understand how it would fix any issues with going offline.

Also another thing about going offline is that this module _is_ designed to fail if it hasn't cached a tarball and you try to request it while offline. The `npm` CLI should not blithely continue if the network request fails.

**Comment by nolanlawson** [comment]
Oh sorry, didn't read https://github.com/nolanlawson/local-npm/issues/104. Based on that issue, it seems like the real issue is that you want to increase the timeout. Is that correct?

**Comment by DrorT** [comment]
Hey Nolan.

I tried increasing the timeout, but it seems that on bad connection there might be situations where the reply can come back after up to 5min (I know my connection at times is terrible) and it seems unreasonable to increase the timeout to that level. Also part of the problem is that when local-npm fails the npm install process keeps running unaware that there is nothing on the other end.

So my solution was to pass the failure to the npm install process, this way npm can request the package again and at the end fail showing the user that a specific package could not be retrieved.

Dror

**Comment by nolanlawson** [comment]
@DrorT OK, so I'm still not quite understanding how this PR changes the existing behavior? Aren't timeouts still passed as errors to the npm CLI?

**Comment by DrorT** [comment]
Hey @nolanlawson,
Before this change local-npm use to crash on timeouts, but the nom cli will keep on running trying to connect and will never stop.
with this change npm cli is notified the file cannot be retrieved and will retry or fail the package.
Since the npm cli is a "monitored" process by the developer but local-npm is less likely to be monitored, with this fix the problem is shown to the developer who can then rerun npm install and/or check his connection.

**Comment by nolanlawson** [comment]
I just double-checked the `request` docs and realized you're right. I thought `pipe()` would propagate errors to the caller, but apparently you have to do `.on('error')` as well. Shows what I know about streams. :stuck_out_tongue: 

Anyway thanks for the PR, will merge and publish a fix shortly.

**Comment by nolanlawson** [comment]
05062069bb1444d2f277d045c1372f6ca6e1d6a0

**Comment by DrorT** [comment]
Thanks :)

**Comment by nolanlawson** [comment]
nice! glad to hear it. :)

**Comment by gr2m** [comment]
I can second that. `local-npm` is such a no-brainer, I use it every day! Thanks for the amazing work :clap:

**Pull request closed without merging**
